#!/bin/sh
# Runs xmodmap if mappings are found. Useful for re-arranging mouse buttons.
# Place this file in /etc/X11/Xsession.d.
# Based on the example script in the Xsession manpage.

SYSMODMAP=/etc/X11/Xmodmap
USRMODMAP=$HOME/.Xmodmap

if [ -x /usr/bin/X11/xmodmap ]; then
  if [ -f $SYSMODMAP ]; then
    xmodmap $SYSMODMAP
  fi
fi

if [ -x /usr/bin/X11/xmodmap ]; then
  if [ -f $USRMODMAP ]; then
    xmodmap $USRMODMAP
  fi
fi
